### ISSUE TITLE
Git Best Practices

### ISSUE THREAD

**Issue by thespidermaned** [splunk/ansible-role-for-splunk#12]
First off, this is awesome!

We’re now bringing in Ansible to our environment and starting git from fresh. I dont want to screw this up so I am asking for some advice.

We have three environments, DEV, PAT and PROD and three separate repos. This is mostly because configs that make sense in DEV may not make sense in PROD. (Directories are different, servers are different etc).

What’s the best way to set up my directory structure for git? Would it be to use a single git repo per environment? Or should I maybe use a repo just for the SHC and another repo for HF?

Looking for just some general advice and best practices. Trying to set us up not to pull our hair out in the future.

Thanks!

**Comment by mason-splunk** [comment]
Are you referring to git repos that contain the apps/TAs/configs that you want to manage across different environments, or for setting up your inventories/host_vars/group_vars to point to map said repos to the hosts in each environment? 

Assuming the former, for apps/TAs/configs, internally we use a separate repo for each app/TA. If you have different versions of the same app/TA in different environments, you could use branches for each, but I think it's cleaner/easier to just use separate projects in Git - i.e. one project per environment and each project contains all the app/TA/config repos for each environment. Internally, we don't really have this problem as when we want to test a new version of something, we update the app/TA/config repo with a new git tag, then deploy that version into dev (while prod still remains on the older version since it has a separate set of inventory variables). Once the new version has been tested in dev, we simply update the `git_version` variable for our prod environment to use the same version that was tested in dev.

For inventory setup, I would just use one repo for all environments. In the case that you have different access requirements for each environment (e.g. different people should be able to see/modify the inventories/vars for their respective environment), then you would want separate repos so that you can permission them differently.

Quick tip: If you have variables that cross over multiple environments (e.g. git ssh key, ansible_user, etc.) you can create a "common" environment and an "all.yml" group_vars. Then, when you run the playbook you can specify multiple inventories - e.g. `ansible-playbook configure_apps.yml -i environments/common/inventory.yml -i  environments/prod/inventory.yml`
