### ISSUE TITLE
Enhancement: Use ini_file instead of a template for deploymentclient.conf and extend functionality

### ISSUE THREAD

**Issue by mason-splunk** [splunk/ansible-role-for-splunk#35]
1. Use ini_file for deploymentclient.conf config instead of template to avoid overwriting potential existing files/other settings
2. Add support for `phoneHomeIntervalInSecs` in [deploymentclient.conf](https://docs.splunk.com/Documentation/Splunk/latest/Admin/deploymentclientconf)
3. Add support for `pass4symmkey` under the `deployment` stanza of [server.conf](https://docs.splunk.com/Documentation/Splunk/latest/Admin/Serverconf#Deployment_Configuration_details)

**Comment by chrisbalmer** [comment]
Using ini_file leaves room for manual changes to persist on a server instead of making sure the config is managed by Ansible. If the goal is to support any configs, you could use a loop in the template over a two layer deep dictionary. i.e.

```yaml
- deploymentclient_settings:
  - stanza1:
    - setting1: value1
    - setting2: value2
  - stanza2:
    - setting1: value1
```

Then in the template, a couple nested for loops to run through the dictionaries. I know you mention not overwriting other settings but if the goal is to manage it via Ansible, you'd want it to be declarative and avoid an engineer/admin accidentally leaving manual configs in the file.
