### ISSUE TITLE
systemd start fail on installation - polkit ask root password or sudo

### ISSUE THREAD

**Issue by spegghy69** [splunk/ansible-role-for-splunk#97]
Installing splunk  on Centos  , fail with 
"Systemd manages the Splunk service. Use 'systemctl start Splunkd' to start the service. Root permission is required. Login as root user or use sudo."]}

The problem seems due to polkit tool using systemd: it's necessary to run /opt/splunk/bin/splunk start with sudo as  reported here:
https://www.duanewaddle.com/splunk-7-2-2-and-systemd/

Using init.d work correctly

**Comment by mason-splunk** [comment]
When you use systemd, you should not use `/opt/splunk/bin/splunk start|stop|restart`. As stated in the error message, you need to use `sudo systemctl start|stop|restart Splunkd` instead. 

This role relies entirely on the service module to handle splunk stop/start/restart, so I'm assuming you're encountering this error while using the CLI? If that is not the case, please provide the steps needed to reproduce.

**Comment by mason-splunk** [comment]
Tested latest version of role using systemd installation with example install playbook and splunk installed without issue. Ran additional play using `deployment_task: splunk_restart.yml` and no issue encountered there either. Role is working as intended.

Tested via CLI, sudo'd to splunk user then attempted `/opt/splunk/bin/splunk restart` and the OS throws error that authentication is required, which is expected behavior since root permission is required to restart systemd services. Exited out of the splunk user and performed a `sudo systemctl restart Splunkd.service` and the Splunkd service restarts as expected. 

The role is working as intended. There are a number of posts about running splunk via systemd vs init.d on community.splunk.com but this topic is also covered in Splunk Docs if you'd like to read-up on it: https://docs.splunk.com/Documentation/Splunk/8.2.2/Workloads/Configuresystemd

**Comment by spegghy69** [comment]
I tried to install splunk using ansible playbook on a fresh centos7 and on a freshcentos8 platform. 
I run the playbook using ansadmin user (not root) , attached my playbook


---
- hosts:
    - all
  serial: 51


  vars:
    - deployment_task: check_splunk.yml
    - ansible_user: ansadmin
    - ansible_ssh_private_key_file: /home/ansadmin/.ssh/id_rsa
    - splunk_user_seed: true
    - splunk_package_url_full: https://d7wz6hmoaavd0.cloudfront.net/products/splunk/releases/8.1.1/linux/splunk-8.1.1-08187535c166-Linux-x86_64.tgz

  pre_tasks:
    - name: print the secure variable
      debug:
        msg: |
          admin {{ splunk_admin_username }}
          password {{ splunk_admin_password }}


  roles:
    - mason_splunk.ansible_role_for_splunk.splunk

**Comment by mason-splunk** [comment]
Is ansadmin a member of sudoers?

**Comment by spegghy69** [comment]
Yes, It is.

**Comment by 7h3sil3nce** [comment]
User splunk should not be in the sudo wheel

**Comment by spegghy69** [comment]
we are not talking about splunk user
